// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0DAdPySz3WB8qh2YHIVXQE7SPDD7RXCY',
    appId: '1:121191550586:web:40cf867b2d4fb422d135c3',
    messagingSenderId: '121191550586',
    projectId: 'todo-list-app-cristian-cruz',
    authDomain: 'todo-list-app-cristian-cruz.firebaseapp.com',
    storageBucket: 'todo-list-app-cristian-cruz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj9KTGmXEUWAVoRq0q-L0u_x715v7Fwp4',
    appId: '1:121191550586:android:5995a234c1f779ced135c3',
    messagingSenderId: '121191550586',
    projectId: 'todo-list-app-cristian-cruz',
    storageBucket: 'todo-list-app-cristian-cruz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOJ3RpB25Ros4znFYGf1BxeJg2aBvVhVs',
    appId: '1:121191550586:ios:4252368fb7793c0bd135c3',
    messagingSenderId: '121191550586',
    projectId: 'todo-list-app-cristian-cruz',
    storageBucket: 'todo-list-app-cristian-cruz.appspot.com',
    androidClientId: '121191550586-ci4ke8i45281qqvsn6d8grjaijktpg4m.apps.googleusercontent.com',
    iosClientId: '121191550586-3th7r5d93ha347kjeo3ro2d9gv04q45u.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOJ3RpB25Ros4znFYGf1BxeJg2aBvVhVs',
    appId: '1:121191550586:ios:55b97464710f6c35d135c3',
    messagingSenderId: '121191550586',
    projectId: 'todo-list-app-cristian-cruz',
    storageBucket: 'todo-list-app-cristian-cruz.appspot.com',
    androidClientId: '121191550586-ci4ke8i45281qqvsn6d8grjaijktpg4m.apps.googleusercontent.com',
    iosClientId: '121191550586-49mpiieqafp2kem36lvgpvt320e0qses.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListApp.RunnerTests',
  );
}
